---
title: "Midterm Revision"
affiliation: "Основи програмування"
author: Vadym Katsel
date: today
date-format: "YYYY-MM-DD"
toc: true
lang: ua
format: 
  html:
    theme:
      light: cosmo
      dark: darkly
---

## 📝 Завдання 1

:::callout-note
### ТЗ
Напишіть програму, яка розраховує кінцеву суму транзакції. Для цього, запитайте в користувача суму транзакції (зчитати з консолі дійсне число). Якщо сума перевищує 1200.00, банк стягує комісію у розмірі 1.5% від суми. В іншому випадку комісія не стягується. Виведіть на екран суму комісії та кінцеву суму до сплати
:::

### Як вирішувати?

- Запитати у користувача суму транзакції
- Перевірити, чи перевищує сума 1200.00
- Якщо так, обчислити комісію як 1.5% від суми
- Вивести комісію та кінцеву суму до сплати

## 📝 Завдання 2

:::callout-note
### ТЗ
Створіть список monthly_profit з 12 дійсних чисел (від -3000 до 3000). Значення обирайте випадковим чином самостійно.

Отже, у вашій програмі надано список monthly_profit, який містить фінансові результати компанії за рік, починаючи із січня.

*Додатні числа — це прибуток.*
*Від'ємні числа — це збиток.*

Напишіть програмний код, з використанням якого, буде знаходитися перший місяць, у якому компанія зазнала збитків (прибуток менше 0), і виводить на екран його порядковий номер. 

Зверніть увагу, що програмний код має виконуватися для будь-якого списку monthly_profit, що відповідає умові. Тобто, якщо викладач замінить значення у списку, кож має працювати коректно.
:::

### Як вирішувати?

- Створити список `monthly_profit`
- Ітеруватися по списку з використанням циклу
- Перевірити кожне значення на від'ємність
- Якщо знайдено від'ємне значення, вивести його порядковий номер і припинити цикл

## 📝 Завдання 3

:::callout-note
### ТЗ
Користувач має ввести з клавіатури ціни на 10 товарів у доларах США.

Поточний курс долара становить 41.5 грн.

Напишіть програму, яка:

- Приймає 10 чисел (ціни в доларах). Кожне нове число запитується з нового рядка.

- Переводить кожну ціну в гривні.

- Зберігає у новий список лише ті ціни в гривнях, які не перевищують 1000 грн (бюджетні товари).

- Виводить підсумковий список бюджетних цін на екран.
:::

### Приклад введення/виведення
```markdown
Введіть 10 цін у USD.

Enter price 1 (USD): 20
Enter price 2 (USD): 5
Enter price 3 (USD): 25
Enter price 4 (USD): 1
Enter price 5 (USD): 15
Enter price 6 (USD): 30
Enter price 7 (USD): 24
Enter price 8 (USD): 2
Enter price 9 (USD): 18
Enter price 10 (USD): 50

Підсумковий список бюджетних цін (до 1000.0 грн):
[830.0, 207.5, 41.5, 622.5, 996.0, 83.0, 747.0]
```

### Як вирішувати?

- Створити порожній список для збереження бюджетних цін
- За допомогою циклу прийняти 10 цін від користувача
- Перевести кожну ціну в гривні, помноживши на 41.5
- Якщо переведена ціна менша за 1000 гривень - додаємо її до списку
- Врешті, виводимо список бюджетних цін на екран

## 📝 Завдання 4

:::callout-note
### ТЗ
Перед вами стоїть задача написати “Симулятор банкомату”.

Програма має працювати наступним чином:

-  Спочатку ви маєте показати користувачу меню доступних операцій:
  1. Перевірити баланс
  2. Зняти гроші
  3. Поповнити рахунок
  4. Вийти

-  В залежності від вибраної операції (користувач має увести відповідний номер), програма має виконати відповідну дію.

-  Баланс користувача початково встановлюється на 1000 гривень.

-  Якщо користувач вводить недоступну команду (що завгодно окрім 1, 2, 3 чи 4), програма має вивести повідомлення про помилку і знову показати меню. - Програма працює доти, доки користувач не обере завершити роботу (опція 4).
:::

### Приклад введення/виведення
```markdown
------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 1

--- Ваш поточний баланс: 1000.00 грн ---

------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 3
Введіть суму поповнення (грн): 200.50

Рахунок успішно поповнено на 200.50 грн.

------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 2
Введіть суму зняття (грн): 500

Успішно знято 500.00 грн.

------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 2
Введіть суму зняття (грн): 800

Помилка: Недостатньо коштів або сума недійсна/від'ємна.

------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 9

*** Помилка: Невірна команда. Спробуйте ще раз (1-4). ***

------------------------------------
Симулятор Банкомату
1. Перевірити баланс
2. Зняти гроші
3. Поповнити рахунок
4. Вийти
------------------------------------
Введіть операцію (1, 2, 3, 4): 4

Дякуємо за користування! До побачення.
```

### Як вирішувати?

- Встановити початковий баланс користувача на 1000 гривень
- Запустити цикл роботи банкомату
- Показати меню доступних операцій та попросити ввід
- В залежності від вибору користувача виконати відповідну дію:
  - Якщо вибір 1: показати поточний баланс
  - Якщо вибір 2: запросити суму для зняття, перевірити наявність коштів, оновити баланс
  - Якщо вибір 3: запросити суму для поповнення, оновити баланс
  - Якщо вибір 4: завершити роботу програми
  - Якщо недійсний ввід: вивести повідомлення про помилку і повторити цикл

