---
title: "Практична №1"
affiliation: "Основи програмування"
date: "10-21-2025"
toc: true
lang: ua
format: 
  html:
    theme:
      light: cosmo
      dark: darkly
---

# 📌 Завдання 1

Уявіть, що Вам необхідно написати простий калькулятор вартості обіду для ресторану. Вам необхідно, аби в користувача була можливість увести назву страви, її ціну, кількість замовлених порцій та знижку. Також необхідно врахувати, що на вартість обіду впливає податок на додану вартість (ПДВ), який становить 20%.

Приклад виконання програми:

``` markdown
Enter the name of the dish: Borshch
Enter the price of the dish: 100
Enter the quantity of portions: 2
Enter the discount (%): 10

The total of <quantity> <name> will be <total> UAH, including <tax> UAH tax.
```

# 🔍 Поради щодо виконання.

1.  Використовуйте функцію `input()` для отримання даних від користувача.
2.  Перетворюйте введені дані у відповідні типи (наприклад, `float` для ціни та знижки, `int` для кількості).
3.  Використовуйте змінні для збереження введених даних та обчислень.
4.  Для того, щоб вивести результат, використовуйте функцію `print()` та форматовані рядки.

::: callout-tip
Для цього завдання, ми знехтуємо правильністю вводу користувача, та приймемо як належне те, що користувач уводить тільки правильні дані.
:::
